Interiror grid fix
Becksteinlab/hollow pull request #3
Opened 2022-03-01 06:44 UTC by ChenouZhang

Now hollow behaves as expected(not creating HOLLOW interior grid anymore).

2022-03-01 16:13 UTC, orbeckst requested changes
Can we make this configurable, i.e., have a setting in the input file or a command line flag? The default should be the old behavior. 

It's very confusing to have tools that behave differently from the original.

2022-07-29 18:33 UTC, orbeckst commented
@ChenouZhang can you please address my comments so that we can get this merged?

Also, @rsexton2 might want to use it.

2022-07-29 20:59 UTC, ChenouZhang commented
@orbeckst I added flag -i to make it consistent.

2022-07-29 21:32 UTC, orbeckst requested changes
Using an optional argument works. Just make it a boolean and see comments on communicating with the user.

EDIT: And importantly: edit the real `hollow` script that is installed.

2022-07-29 21:32 UTC, orbeckst commented on build/scripts-2.7/hollow
> +from hollow.core import make_hollow_spheres, defaults, help
I don't think the scripts under build should ever be touched, instead modify the scripts under `scripts`, which are installed.

https://github.com/Becksteinlab/hollow/blob/Interiror-Grid-Fix/scripts/hollow

2022-07-29 21:32 UTC, orbeckst commented on build/scripts-2.7/hollow
> +      default='yes')
Make it a boolean switch (choose the proper type with `action="store_false"` ) and set the default as `True`.

2022-07-29 21:32 UTC, orbeckst commented on build/scripts-2.7/hollow
> +      help="Enable/disable the grid.exclude_surrounded " \
Describe in words what it does, nobody knows what grid.exclude_surrounded does.

2022-07-29 21:32 UTC, orbeckst commented on hollow/core.py
> +  if is_hollow == 'yes':
use a boolean, not string comparison

2022-07-29 21:32 UTC, orbeckst commented on hollow/core.py
> +  print 'is_hollow has been set to: %s' % is_hollow
A user has no idea what "is_hollow" means. Say in words what happens. 

Maybe refer to the `-i` option of hollow. But think about the messages from the user's perspective.

2022-07-29 21:32 UTC, orbeckst commented on hollow/hollow.txt
> +  'is_hollow': 'yes'
boolean!

2022-07-29 23:24 UTC, ChenouZhang commented
@orbeckst updated as requested.

2022-07-30 01:27 UTC, orbeckst approved these changes
thanks for the changes; I am fixing a few things myself and then merge

2022-07-30 01:27 UTC, orbeckst commented on scripts/hollow
> +#!/nfs/homes4/chenou/anaconda3/envs/Born/bin/python
needs to stay the /usr/bin/env

2022-07-30 01:27 UTC, orbeckst commented on hollow/core.py
> +  print 'is_hollow has been set to: %r' % is_hollow
see my earlier comment — make it clearer

2022-07-30 01:27 UTC, orbeckst commented on hollow/core.py
> +    pass
remove — can just be the if statement without else
```suggestion
```

2022-07-30 01:27 UTC, orbeckst commented on scripts/hollow
> +#!/nfs/homes4/chenou/anaconda3/envs/Born/bin/python
```suggestion
#!/usr/bin/env python
```

2022-07-30 01:27 UTC, orbeckst commented on hollow/core.py
> +  print 'is_hollow has been set to: %r' % is_hollow
```suggestion
  print 'is_hollow (hollow -i commandline option) has been set to: %r' % is_hollow
```

2022-07-30 01:28 UTC, merged

2022-07-30 01:29 UTC, orbeckst commented
@rsexton2 you should now be able to use `hollow -i` to make it fill the interior with spheres.